const admin = require("../config/firebase");
const jwt = require("jsonwebtoken");

const JWT_SECRET = process.env.JWT_SECRET || "your_secret_key_change_in_prod";

const verifyToken = async (req, res, next) => {
  const authHeader = req.headers.authorization;

  // 1. Check if token exists
  if (!authHeader || !authHeader.startsWith("Bearer ")) {
    return res.status(401).json({ error: "No token provided" });
  }

  const token = authHeader.split(" ")[1];
  console.log("Backend received token:", token ? `${token.substring(0, 20)}...` : "No token");

  try {
    // 2. Try to verify as JWT token first (generated by our server)
    try {
      console.log("Attempting JWT verification with secret:", JWT_SECRET.substring(0, 10) + "...");
      const decodedToken = jwt.verify(token, JWT_SECRET);
      req.user = decodedToken;
      console.log("✅ JWT verification successful for user ID:", decodedToken._id || decodedToken.sub);
      return next();
    } catch (jwtErr) {
      console.log("JWT verification failed:", jwtErr.message);
      console.log("JWT error name:", jwtErr.name);
      
      // Handle expired tokens specifically
      if (jwtErr.name === 'TokenExpiredError') {
        console.log("⚠️ Token expired - user needs to re-authenticate");
        return res.status(401).json({ 
          error: "Token expired", 
          message: "Your session has expired. Please log in again.",
          code: "TOKEN_EXPIRED"
        });
      }
      
      console.log("Trying Firebase...");
      // Fall through to Firebase verification
    }

    // 3. Try Firebase verification as fallback
    try {
      const decodedToken = await admin.auth().verifyIdToken(token, true); // Add checkRevoked=true
      req.user = decodedToken;
      console.log("✅ Firebase verification successful");
      return next();
    } catch (firebaseErr) {
      console.error("Firebase verification failed:", firebaseErr.message);
      throw new Error("Invalid token - neither server JWT nor valid Firebase ID token");
    }
  } catch (error) {
    console.error("Token verification failed:", error.message);
    res.status(403).json({ error: "Unauthorized: Invalid token" });
  }
};

module.exports = verifyToken;
