const admin = require("../config/firebase");
const jwt = require("jsonwebtoken");
const { User } = require("../models/Schema");

// Check for required environment variable
if (!process.env.JWT_SECRET) {
  throw new Error("JWT_SECRET environment variable is required for security");
}

const JWT_SECRET = process.env.JWT_SECRET;

const verifyToken = async (req, res, next) => {
  const authHeader = req.headers.authorization;

  // 1. Check if token exists
  if (!authHeader || !authHeader.startsWith("Bearer ")) {
    return res.status(401).json({ error: "No token provided" });
  }

  const token = authHeader.split(" ")[1];

  try {
    let userId;

    // 2. Try to verify as JWT token first (generated by our server)
    try {
      const decodedToken = jwt.verify(token, JWT_SECRET);
      userId = decodedToken._id || decodedToken.sub;
    } catch (jwtErr) {
      console.error("JWT verification failed:", jwtErr.message);

      // Handle expired tokens specifically
      if (jwtErr.name === 'TokenExpiredError') {
        return res.status(401).json({
          error: "Token expired",
          message: "Your session has expired. Please log in again.",
          code: "TOKEN_EXPIRED"
        });
      }

      // Fall through to Firebase verification
    }

    // 3. If JWT failed, try Firebase verification
    if (!userId) {
      try {
        const decodedToken = await admin.auth().verifyIdToken(token, true); // Add checkRevoked=true
        userId = decodedToken.uid;
      } catch (firebaseErr) {
        console.error("Firebase verification failed:", firebaseErr.message);
        throw new Error("Invalid token - neither server JWT nor valid Firebase ID token");
      }
    }

    // 4. Fetch the full user document from database
    try {
      const user = await User.findById(userId).select('-password'); // Exclude password field
      if (!user) {
        return res.status(401).json({ error: "User not found" });
      }

      // Attach the full user document to req.user
      req.user = {
        _id: user._id,
        name: user.name,
        email: user.email,
        isAdmin: user.isAdmin || false,
        isPremium: user.isPremium || false,
        isActive: user.isActive !== false, // Default to true if not set
        // Add other fields as needed
      };

      return next();
    } catch (dbErr) {
      console.error("Database error during user fetch:", dbErr.message);
      return res.status(500).json({ error: "Database error" });
    }
  } catch (error) {
    console.error("Token verification failed:", error.message);
    res.status(403).json({ error: "Unauthorized: Invalid token" });
  }
};

module.exports = verifyToken;
